//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_access_layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public Nullable<int> FromId { get; set; }
        public Nullable<int> ToId { get; set; }
        public Nullable<int> ReciepeId { get; set; }
        public string MessageString { get; set; }
    
        public virtual User User { get; set; }
        public virtual Reciepe Reciepe { get; set; }
        public virtual User User1 { get; set; }
    }
}
